### ISSUE TITLE
rosie project metadata

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1341]
> We need to decide:
>  * how to name `project` metadata for `rose-suite.info` files
>  * where to store this metadata (in a prefix-specific special Rosie suite?)
>  * whether we can support prefix-specific metadata (or is this a bad idea?)

We have decided to have prefix-specific metadata within the special Rosie suites. Each metadata directory will have its parent prefix - e.g. `meto-foobar` for a prefix `meto`. The `project` option in the `rose-suite.info` file will also contain this prefix.

To reference the `meto-foobar` metadata directory, the `rose-suite.info` file would have to have `project=meto-foobar`.

The above does not require any work in software, but there are a few extra issues to consider:
 - [ ] - server-side checking of project metadata. MOVED to #1702.
 - [x] - `rosie create` and `rosie copy` checking of project metadata (`rosie create` probably requires a double step if project metadata is found, both will require a looping process for the user to get it right) MOVED to #1632
 - [x] - `copy-mode` (`=never`, `=clear`...) new metadata option, to disallow certain project-metadata-specific option values from being copied automatically from one `rose-suite.info` to another (e.g. clear the value). MOVED to #1632
 - [ ] - `rosie copy` from one prefix to another, managing any prefix-specific project flag. MOVED to #1691 as considered very different from server-side checking

**Comment by benfitzpatrick** [comment]
@dpmatthews, I think this issue captures what we need.

**Comment by matthewrmshin** [comment]
See also #1337.

**Comment by arjclark** [comment]
@benfitzpatrick - might be time to take another look at this as the driving project is moving closer.

**Comment by matthewrmshin** [comment]
Close as all items in check list done or moved to separate issues.
